### ISSUE TITLE
TypeError: Keras symbolic inputs/outputs do not implement `__len__`

### ISSUE THREAD

**Issue by LIUDENGBOcode** [hkthirano/targeted_UAP_CIFAR10#2]
How to solve the following problem？
[tensorflow-gpu==2.10.1, keras==2.10.0]

Traceback (most recent call last):
  File "targeted_UAP_CIFAR10/generate_noise.py", line 90, in <module>
    classifier = KerasClassifier(model=model)
  File "adversarial-robustness-toolbox/art/classifiers/keras.py", line 84, in __init__
    self._initialize_params(model, use_logits, input_layer, output_layer)
  File "adversarial-robustness-toolbox/art/classifiers/keras.py", line 171, in _initialize_params
    if predictions == self._input:
  File "miniconda3/envs/python3.7/lib/python3.7/site-packages/keras/engine/keras_tensor.py", line 245, in __len__
    "Keras symbolic inputs/outputs do not "

TypeError: Keras symbolic inputs/outputs do not implement `__len__`. You may be trying to pass Keras symbolic inputs/outputs to a TF API that does not register dispatching, preventing Keras from automatically converting the API call to a lambda layer in the Functional Model. This error will also get raised if you try asserting a symbolic input/output directly.

**Comment by kztakemoto** [comment]
Sorry for late reply.
Our repository assumes tensorflow-gpu==1.15.5 and Keras==2.2.5.

For TF2, ART library, in which our targeted UAP is available, needs to be used.
Please see the following notebook for details.
https://colab.research.google.com/drive/1ay_4otbY1qHyWvYdR5vqMMUk4tABCz7D?usp=sharing
